discord: PUTYOURDISCORDBOTKEYHERE
character: character.json

embeddings:
  model: hkunlp/instructor-xl

llm: hermes-ggml-4bit

hermes-ggml-4bit:
  model: TheBloke/Nous-Hermes-13B-GGML
  model_file: nous-hermes-13b.ggmlv3.q4-0.bin
  model_type: llama
  config:
    context_length: 2048

ctransformers:
  model: TheBloke/Wizard-Vicuna-7B-Uncensored-GGML
  model_file: Wizard-Vicuna-7B-Uncensored.ggmlv3.q4_0.bin
  model_type: llama
  config:
    context_length: 1024

huggingface:
  model: TheBloke/Wizard-Vicuna-7B-Uncensored-HF
  pipeline_kwargs:
    max_new_tokens: 256

gptq:
  model: TheBloke/Wizard-Vicuna-7B-Uncensored-GPTQ
  model_file: Wizard-Vicuna-7B-Uncensored-GPTQ-4bit-128g.no-act-order.safetensors
  pipeline_kwargs:
    max_new_tokens: 256

download: false

host: localhost
port: 5000

chroma:
  persist_directory: db
  chroma_db_impl: duckdb+parquet
  anonymized_telemetry: false

retriever:
  search_kwargs:
    k: 4
